### ISSUE TITLE
Project Size

### ISSUE THREAD

**Issue by Stem76** [AceSardonyx/NEI#3]
Is the **./build** folder needed in the GitHub rep or can it get removed?
It takes up _488 MB_ of space to have and it looks like its just binaries to start the mod locally.
If not needed we could simply add it to the **.gitignore**
If needed please explain why so I know, I'm new to Minecraft Mod making and maybe this is an essential part of the mod but I just simply don't know it.

**Comment by AceSardonyx** [comment]
I will see if is redownloaded or not.
Will also set something up to download it when chosen if needed since they are static files.

**Comment by Stem76** [comment]
From what I saw when I looked fast was some temp files and other dynamic files that change every time you made a new commit.
When I wake up I can make a new branch and test to delete the ./build folder and see if it still works, then you can look at it so it all works at your end and then we would have more knowledge about what to do about it.

Thanks for fast reply👍🏻

**Comment by AceSardonyx** [comment]
I'm testing it rn lol.
Also that is strange, it should be static...
I was probably thinking of something else

**Comment by Stem76** [comment]
> I'm testing it rn lol. Also that is strange, it should be static... I was probably thinking of something else

Nice nice, if you find anything write it in here and I'll read it tomorrow morning 👍🏻

**Comment by AceSardonyx** [comment]
It is a relative file with files that cannot regenerate.
When attempting to remove, they do not regenerate correct due to mismatches, etc.
The binaries are used by a few programs to compile the java project with ease and easily edit it.
And like you said to also start the mod locally. So it is needed.
Also, is the size too much of an issue? I've never had storage problems with GitHub. Cloning doesn't take too long either.
Keep in mind I use a 50mbps at max network and use a 60gb storage laptop.
If it is an issue, I will just implement what I've previously said.

**Comment by AceSardonyx** [comment]
On the other hand, I have found a resolution by adding caches to the .gitignore that *do* regenerate.
It shaves off about 400mb. Do still read my comment above though :)

**Comment by Stem76** [comment]
> On the other hand, I have found a resolution by adding caches to the .gitignore that _do_ regenerate. It shaves off about 400mb. Do still read my comment above though :)

Nicely done!
Then its less clutter in the commits too
